### ISSUE TITLE
Save for Later

### ISSUE THREAD

**Issue by StephenOTT** [zikula/Wizard#2]
Any thoughts on handling a Save for Later type of action?

This could be partial wizard completion (completed 3 our of 7 stages, and then chose to close and come back later).   But could also be halfway through a specific stage, filled out 3 of the 5 form fields, but I wish to save, close, and come back to the partially filled out stage later on.

**Comment by craigh** [comment]
Hi @StephenOTT thanks for your ticket. Sadly, I do not have any ideas, but this is only because I haven't looked at this code much in the last year or two. If you find a way and would like to contribute your code back to the repo, that would be terrific! thanks again for your idea.

**Comment by StephenOTT** [comment]
@craigh thanks
